import customHtml from '!!raw-loader!./custom/custom.html?raw';
import customSass from '!!raw-loader!./custom/custom.scss';
import customCode from '!!raw-loader!./custom/custom';
import disableRippleHtml from '!!raw-loader!./disable-ripple/disable-ripple.html?raw';
import singleLineHtml from '!!raw-loader!./single-line/single-line.html?raw';
import twoLineHtml from '!!raw-loader!./two-line/two-line.html?raw';
import leadingIconHtml from '!!raw-loader!./leading-icon/leading-icon.html?raw';
import trailingIconHtml from '!!raw-loader!./trailing-icon/trailing-icon.html?raw';
import leadingTrailingIconHtml from '!!raw-loader!./leading-trailing-icon/leading-trailing-icon.html?raw';
import twoLineLeadingTrailingIconHtml from '!!raw-loader!./two-line-leading-trailing-icon/two-line-leading-trailing-icon.html?raw';
import leadingCheckboxHtml from '!!raw-loader!./leading-checkbox/leading-checkbox.html?raw';
import trailingCheckboxHtml from '!!raw-loader!./trailing-checkbox/trailing-checkbox.html?raw';
import avatarHtml from '!!raw-loader!./avatar/avatar.html?raw';
import groupHtml from '!!raw-loader!./group/group.html?raw';
import expandableHtml from '!!raw-loader!./expandable/expandable.html?raw';

import { Avatar } from './avatar/avatar';
import { Custom } from './custom/custom';
import { DisableRipple } from './disable-ripple/disable-ripple';
import { Expandable } from './expandable/expandable';
import { Group } from './group/group';
import { LeadingCheckbox } from './leading-checkbox/leading-checkbox';
import { LeadingIcon } from './leading-icon/leading-icon';
import { LeadingTrailingIcon } from './leading-trailing-icon/leading-trailing-icon';
import { SingleLine } from './single-line/single-line';
import { TrailingCheckbox } from './trailing-checkbox/trailing-checkbox';
import { TrailingIcon } from './trailing-icon/trailing-icon';
import { TwoLine } from './two-line/two-line';
import { TwoLineLeadingTrailingIcon } from './two-line-leading-trailing-icon/two-line-leading-trailing-icon';

export class ListExamples {
  customHtml = customHtml;
  customSass = customSass;
  customCode = customCode;
  disableRippleHtml = disableRippleHtml;
  singleLineHtml = singleLineHtml;
  twoLineHtml = twoLineHtml;
  leadingIconHtml = leadingIconHtml;
  trailingIconHtml = trailingIconHtml;
  leadingTrailingIconHtml = leadingTrailingIconHtml;
  twoLineLeadingTrailingIconHtml = twoLineLeadingTrailingIconHtml;
  leadingCheckboxHtml = leadingCheckboxHtml;
  trailingCheckboxHtml = trailingCheckboxHtml;
  avatarHtml = avatarHtml;
  groupHtml = groupHtml;
  expandableHtml = expandableHtml;

  avatar = Avatar;
  custom = Custom;
  disableRipple = DisableRipple;
  expandable = Expandable;
  group = Group;
  leadingCheckbox = LeadingCheckbox;
  leadingIcon = LeadingIcon;
  leadingTrailingIcon = LeadingTrailingIcon;
  singleLine = SingleLine;
  trailingCheckbox = TrailingCheckbox;
  trailingIcon = TrailingIcon;
  twoLine = TwoLine;
  twoLineLeadingTrailingIcon = TwoLineLeadingTrailingIcon;
}
